### ISSUE TITLE
运行出现error

### ISSUE THREAD

**Issue by Laurc2004** [BigOrangeQWQ/nonebot_plugin_acm_reminder#2]
![image](https://user-images.githubusercontent.com/119660750/224754397-f6e0fc46-1d03-4e58-80d0-42b34022ab61.png)

**Comment by BigOrangeQWQ** [comment]
type hint标注出现了不兼容的状况
明天会发一个版修复这个问题

**Comment by BigOrangeQWQ** [comment]
已发版修复这个问题/w\

**Comment by Laurc2004** [comment]
你好，拉取竞赛列表的更新时间是以分钟为单位吗？起始时间怎么算呢？是从第一次使用contest.list指令开始吗？昨天升级了python版本使用该插件后，contest.list无任何问题，但不能定时发送。

**Comment by BigOrangeQWQ** [comment]
**当前版本没有定时发送竞赛列表的功能。**

更新时间以分钟为单位，从Bot启动开始即计时。
这时的更新是更新内存里的竞赛列表，而非发送竞赛信息。

**Comment by Laurc2004** [comment]
明白。
