### ISSUE TITLE
当codeforces出现时长格式为%H:%M:%S的比赛时报错

### ISSUE THREAD

**Issue by verynewabie** [BigOrangeQWQ/nonebot_plugin_acm_reminder#5]
debug了一会，发现时间一会是14:00:00的格式，一会是02:00的格式，导致有个地方报错，上官网一看，好家伙，一枝独秀
![image](https://user-images.githubusercontent.com/88194567/234486528-c806c7d6-adc5-445a-b25a-7047442e4c14.png)

**Comment by BigOrangeQWQ** [comment]
草，神奇的CF，我得想想怎么解决，如果你能pr就最好了:w

**Comment by verynewabie** [comment]
我才接触nonebot2，用的插件都是商店下载的，还没那个能力（

**Comment by BigOrangeQWQ** [comment]
两天内修复这个BUG，静候佳音:l

**Comment by verynewabie** [comment]
修好了踢我一脚

**Comment by BigOrangeQWQ** [comment]
应该大概已经修复了
请下载0.1.7版本

pip install nonebot-plugin-acm-reminder -U
